name: bloodhound-examples
version: '0.0.0.0'
synopsis: Bloodhound's toy projet
description: Bloodhound's toy projet for tweeter addicts
category: Web
author: Chris Allen
maintainer: cma@bitemyapp.com
copyright: 2017, Chris Allen
license: BSD3
github: bitemyapp/bloodhound
extra-source-files:
- README.md
dependencies:
- base >=4.14 && <5
- bloodhound
- aeson
- http-client
- semigroups
- text
- time
- vector
ghc-options:
- -Wall
- -threaded
- -rtsopts
- -with-rtsopts=-N
when:
- condition: flag(werror)
  ghc-options: -Werror

executables:
  tweet-example:
    main: Tweet.hs

flags:
  werror:
    description: "Treat warnings as errors"
    manual: true
    default: false
