name: "Formatting check (ormolu)"
on:
  pull_request:
  push:
jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41
      with:
        # globs copied from default settings for run-ormolu
        files: |
          **/*.hs
          **/*.hs-boot
        separator: "\n"
    - uses: haskell-actions/run-ormolu@v14
      with:
        version: "0.5.3.0"
        pattern: ${{ steps.changed-files.outputs.all_changed_files }}
